/* Generated by u8g2fontgen - do not edit by hand.
 * Source config: fonts.yaml
 */

#ifndef CUSTOM_FONTS_H
#define CUSTOM_FONTS_H

#include <u8g2.h>

extern const uint8_t custom_helvB24[] U8G2_FONT_SECTION("custom_helvB24");
extern const uint8_t custom_helvB08[] U8G2_FONT_SECTION("custom_helvB08");

#endif /* CUSTOM_FONTS_H */
